language: java
jdk: "-openjdk11"
deploy:
  provider: heroku
  api_key:
    secure: AbWOeMcw7hWa/g1tseo4+lVo3U137UymY0NGc29hmMFbdCC5wILoBdFGGNXn4RC3qiX5ckHokt2j61D2Bh0gcHMshoU0X7/Bqteyd3iHWNM6ayVbP+yvHvayhyrXVZGGB73vfeCBrYfmXHobHAsizwjb0XV5HeyB4+frYIfcJcJg4yxQu77ZI7ROF/i1dZE5jzRBiZgSMMBM7GQtcruUrgYFmsLgzRJbPyilcNIKCYg+abFgxi5dqEuBdKDM/6kIquzQ4T+6wn2zAnTT40gtDFkC/6QZKrIwhiY7Zzy/2hZgBfl6ieP8mQzZrfa9IM+RX/YzwUdiMYl8htQQntO4l14ufABAyPe3qnsnJmTMcXnD17icESfVPxW7Dg3o4io7jha3RRKAv6yZ73R33BtwgFql8XXyDvMfD0fEd3jgArJTIwF50b99lpNzQnmxhARpSI28Z8KlUHomMXDuIEWMRlifcZFzokP5drta3ubQMY6w7TieX8E9z3Us7d3CN8PMC8oKbBYTEb4PDpxR5GIzIYs66xBXvGmsTmiycs/pWizKZoH2g1dEFuoc24iyX9wkGiXPm3yM/vvauuIcHHvkLhV80DFs3q4av6pL2l6mXz8frXaIe2vB5dJclwlDzSJBWIvzZMN1Creao/eMBiRCOdBxWEnBDllovE+6l+01Msk=
  app: task-dev
  on:
    all_branches: true
